enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# Good source for patches : https://nvbangg.github.io/awesome-for-morphe/

[YouTube]
enabled = true
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
excluded-patches = "'Custom branding'"

[YouTube-Experimental]
enabled = true
app-name = "YouTube Experimental"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
experimental = true
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
excluded-patches = "'Custom branding'"

[Music]
enabled = true
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
arch = "arm64-v8a"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
excluded-patches = "'Custom branding'"

[Reddit]
enabled = true
app-name = "Reddit"
rv-brand = "Morphe"
build-mode = "apk"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"

[Twitter]
enabled = false
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
build-mode = "apk"
version = "11.81.0-release.0"
include-stock = "split"

[GooglePhotos]
enabled = false
build-mode = "both"
arch = "both"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Twitch]
enabled = false
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[Facebook]
enabled = false
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "DeVanced"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "apk"

[Messenger]
enabled = false
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "DeVanced"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "apk"

[Instagram]
enabled = false
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "apk"

[NiagaraLauncher]
enabled = true
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
uptodown-dlurl = "https://niagara-launcher.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "apk"
info = "Note: You may encounter this bug: https://github.com/hoo-dles/morphe-patches/issues/429"

[ProtonVPN]
enabled = true
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "apk"

[Discord]
enabled = true
rv-brand = "Raincord"
patch-method = "lspatch"
patches-source = "codeberg.org/raincord/rainXposed"
xposed-module-asset = "app-release\\.apk"
discord-dlurl = "auto"
arch = "arm64-v8a"
build-mode = "apk"
