#!/usr/bin/env python3
import os
import glob
import re
import json
import sys
import urllib.parse

# Ensure the scripts/ directory is on the path for sibling imports
sys.path.insert(0, os.path.dirname(__file__))
from apk_utils import get_package_id, extract_apk_icon

# This script runs AFTER releases are built and uploaded.
# The NEXT_VER_CODE environment variable contains the release tag.
from config_utils import get_enabled_apps, get_repo_details, QR_SVG

next_ver_code = os.environ.get("NEXT_VER_CODE", "UNKNOWN_TAG")
owner, repo_name = get_repo_details()

base_url = "https://apk.thetoto.fr"

def get_patch_status(default_enabled, explicitly_enabled, explicitly_disabled, exclusive):
    if explicitly_disabled:
        return "explicitly_disabled"
    if explicitly_enabled:
        return "explicitly_enabled"
    if exclusive:
        return "disabled"
    if default_enabled:
        return "enabled"
    return "disabled"

out_dir = "/tmp/pages"
os.makedirs(out_dir, exist_ok=True)

config_path = sys.argv[1] if len(sys.argv) > 1 else "config.toml"
enabled_apps = get_enabled_apps(config_path)
slug_to_name = {slug: info['name'] for slug, info in enabled_apps.items()}

build_dir = "build"
apks = glob.glob(os.path.join(build_dir, "*.apk"))
built_slugs = set()

for apk_path in apks:
    filename = os.path.basename(apk_path)

    slug = "unknown"
    # Try to match based on expected prefix generated by build.sh
    for s, info in enabled_apps.items():
        app_name = info["name"]
        app_config = info["config"]
        app_name_in_config = app_config.get("app-name", app_name)
        app_name_l = app_name_in_config.lower().replace(' ', '-')
        rv_brand = info["brand"]
        rv_brand_f = rv_brand.lower().replace(' ', '-')
        expected_prefix = f"{app_name_l}-{rv_brand_f}-v"
        if filename.startswith(expected_prefix):
            slug = s
            break

    if slug == "unknown":
        for valid_slug in sorted(slug_to_name.keys(), key=len, reverse=True):
            if filename.startswith(valid_slug + "-"):
                slug = valid_slug
                break
            
    if slug == "unknown":
        parts = filename.split('-')
        slug = parts[0] if parts else "unknown"

    app_info = enabled_apps.get(slug, {})
    app_config = app_info.get("config", {})
    app_display_name = app_config.get("app-name", app_info.get("name", slug.replace('-', ' ').title()))
    built_slugs.add(slug)

    # Resolve Obtainium App ID (Package Name) from apk using aapt
    app_id = get_package_id(apk_path)

    download_url = f"{base_url}/releases/download/{next_ver_code}/{filename}"
    page_url = f"{base_url}/{slug}.html"
    
    icon_filename = f"{slug}.png"
    icon_out_path = os.path.join(build_dir, icon_filename)
    icon_pages_path = os.path.join(out_dir, icon_filename)
    icon_source_path = os.path.join("icons", icon_filename)
    icon_url = f"./{icon_filename}"
    
    if not os.path.exists(icon_out_path):
        if os.path.exists(icon_source_path):
            import shutil
            shutil.copy2(icon_source_path, icon_out_path)
            print(f"Copied static icon from {icon_source_path}")
        else:
            extract_apk_icon(apk_path, icon_out_path)
    
    # Copy icon to pages output dir
    if os.path.exists(icon_out_path) and not os.path.exists(icon_pages_path):
        import shutil
        shutil.copy2(icon_out_path, icon_pages_path)
    
    # Extract info from filename (with fallback values)
    m = re.search(r"^(.*?)-v([0-9a-zA-Z.-]+)-((?:arm64-v8a|arm-v7a|x86_64|x86|all))\.apk$", filename)
    if m:
        brand_extracted = m.group(1)
        brand_extracted = brand_extracted[len(slug)+1:] if brand_extracted.startswith(slug+"-") else brand_extracted
        if not brand_extracted:
            brand_extracted = "Original"
        version = m.group(2)
        arch = m.group(3)
    else:
        brand_extracted, version, arch = "Unknown", "Unknown", "Unknown"

    # Get brand and patches-source from TOML
    app_info = enabled_apps.get(slug, {})
    brand = app_info.get("brand", brand_extracted)
    patches_src = app_info.get("patches-source", "ReVanced/revanced-patches")
    if patches_src.startswith("http://") or patches_src.startswith("https://"):
        brand_link = patches_src
    elif patches_src.startswith("codeberg.org/"):
        brand_link = f"https://{patches_src}"
    else:
        brand_link = f"https://github.com/{patches_src}"

    app_config = app_info.get("config", {})
    patch_method = app_config.get("patch-method", "revanced").strip().lower()
    brand_html = f'<a href="{brand_link}" class="brand-link" target="_blank" rel="noopener">{brand}</a>'
    if patch_method == "lspatch":
        patch_source_display = f"LSPatch: {brand_html}"
    else:
        patch_source_display = brand_html



    # Craft the Obtainium JSON payload
    additional_settings = {
        "versionExtractionRegEx": r"-v([0-9a-zA-Z.-]+)-(arm64-v8a|arm-v7a|x86_64|x86|all)\.apk",
        "matchGroupToUse": "$1",
        "defaultPseudoVersioningMethod": "APKLinkHash",
        "appName": app_display_name,
        "appAuthor": owner,
        "about": f"{app_display_name} {brand}"
    }
    
    app_json = {
        "id": app_id,
        "url": page_url,
        "author": owner,
        "name": app_display_name,
        "preferredApkIndex": 0,
        "additionalSettings": json.dumps(additional_settings)
    }
    json_str = json.dumps(app_json)
    encoded_json = urllib.parse.quote(json_str, safe='')
    obtainium_link = f"obtainium://app/{encoded_json}"

    patches_json_path = apk_path.replace(".apk", ".patches.json")
    patches_list_html = ""
    if os.path.exists(patches_json_path):
        try:
            with open(patches_json_path, "r") as f:
                patches_data = json.load(f)
            if patches_data:
                if isinstance(patches_data, dict):
                    patches = patches_data.get("patches", [])
                    exclusive = patches_data.get("exclusive", False)
                else:
                    patches = patches_data
                    exclusive = False

                processed_patches = []
                applied_count = 0
                for p in patches:
                    name = p.get('name', '')
                    desc = p.get('description', '') or "No description available."
                    if desc.strip().lower() == "null" or not desc:
                        desc = "No description available."
                    default_enabled = p.get('default_enabled', False)
                    if isinstance(default_enabled, str):
                        default_enabled = default_enabled.lower() == "true"
                    explicitly_enabled = p.get('explicitly_enabled', False)
                    if isinstance(explicitly_enabled, str):
                        explicitly_enabled = explicitly_enabled.lower() == "true"
                    explicitly_disabled = p.get('explicitly_disabled', False)
                    if isinstance(explicitly_disabled, str):
                        explicitly_disabled = explicitly_disabled.lower() == "true"
                    
                    status = get_patch_status(default_enabled, explicitly_enabled, explicitly_disabled, exclusive)
                    if status in ("explicitly_enabled", "enabled"):
                        applied_count += 1
                        
                    processed_patches.append({
                        "name": name,
                        "description": desc,
                        "status": status,
                        "default_enabled": default_enabled
                    })
                
                status_order = {
                    "explicitly_disabled": 0,
                    "explicitly_enabled": 1,
                    "enabled": 2,
                    "disabled": 3
                }
                processed_patches.sort(key=lambda x: (status_order.get(x["status"], 4), x["name"].lower()))

                patches_list_html += f"""
        <div class="patches-section">
            <h3 class="patches-title">⚙️ Applied Patches ({applied_count}/{len(processed_patches)})</h3>
            <div class="patches-list">
"""
                for p in processed_patches:
                    status = p["status"]
                    status_class = {
                        "explicitly_disabled": "excluded",
                        "explicitly_enabled": "applied",
                        "enabled": "applied",
                        "disabled": "disabled"
                    }.get(status, "disabled")

                    if status == "explicitly_disabled":
                        status_label = "Explicitly Disabled"
                    elif status == "explicitly_enabled":
                        if p["default_enabled"]:
                            status_label = "Explicitly Enabled (Default)"
                        else:
                            status_label = "Explicitly Enabled (Not Default)"
                    elif status == "enabled":
                        status_label = "Enabled"
                    else:
                        status_label = "Disabled"
                    
                    patches_list_html += f"""
                <div class="patch-card {status_class}">
                    <div class="patch-header">
                        <span class="patch-name">{p['name']}</span>
                        <span class="patch-status status-{status_class}">{status_label}</span>
                    </div>
                    <div class="patch-desc">{p['description']}</div>
                </div>
"""
                patches_list_html += """
            </div>
        </div>
"""
        except Exception as e:
            print(f"Warning: could not read/process patches file for {filename}: {e}")

    info_text = app_config.get("info", "").strip()
    info_card_html = ""
    if info_text:
        # Convert URLs to clickable links
        info_html = re.sub(
            r'(https?://[^\s<]+[^.\s<])',
            r'<a href="\1" target="_blank" rel="noopener">\1</a>',
            info_text
        )
        info_html = info_html.replace("\n", "<br>")
        info_card_html = f"""
        <div class="info-card">
            <div class="info-card-header">
                <span class="info-card-icon">⚠️</span>
                <span class="info-card-title">Warning</span>
            </div>
            <div class="info-card-content">{info_html}</div>
        </div>
"""

    # Check if a Magisk / KernelSU module ZIP exists for this app
    module_zips = glob.glob(os.path.join(build_dir, f"{app_name_l}-{brand.lower().replace(' ', '-')}-module-*.zip"))
    if not module_zips:
        module_zips = glob.glob(os.path.join(build_dir, f"{slug}-*-module-*.zip"))
    if not module_zips:
        module_zips = glob.glob(os.path.join(build_dir, f"{slug}*module*.zip"))

    module_section_html = ""
    module_modals_html = ""
    if module_zips:
        module_path = module_zips[0]
        module_filename = os.path.basename(module_path)
        module_download_url = f"{base_url}/releases/download/{next_ver_code}/{module_filename}"

        module_additional_settings = {
            "versionExtractionRegEx": r"-module-v([0-9a-zA-Z.-]+)-(arm64-v8a|arm-v7a|x86_64|x86|all)\.zip",
            "matchGroupToUse": "$1",
            "isMagiskModule": True,
            "defaultPseudoVersioningMethod": "APKLinkHash",
            "appName": f"{app_display_name} (Magisk/KernelSU)",
            "appAuthor": owner,
            "about": f"{app_display_name} {brand} Magisk Module"
        }

        module_app_json = {
            "id": f"{app_id}.module",
            "url": page_url,
            "author": owner,
            "name": f"{app_display_name} (Magisk/KernelSU)",
            "preferredApkIndex": 0,
            "additionalSettings": json.dumps(module_additional_settings)
        }
        module_encoded_json = urllib.parse.quote(json.dumps(module_app_json), safe='')
        module_obtainium_link = f"obtainium://app/{module_encoded_json}"

        module_section_html = f"""
        <div class="download-card module-card">
            <div class="download-card-header">
                <span class="card-badge module-badge">⚡ Magisk / KernelSU / APatch Module (Root)</span>
            </div>
            <div class="filename-raw">
                File: <code>{module_filename}</code>
            </div>
            <div class="actions-group">
                <div class="action-row">
                    <a href="{module_download_url}" class="btn btn-download-module">Download Module (.zip)</a>
                    <button class="btn-qr" onclick="document.getElementById('qr-modal-module').classList.add('active')" title="Show Module QR Code">
                        {QR_SVG}
                    </button>
                </div>
            </div>
            <div class="module-notice">
                <span class="notice-icon">💡</span>
                <span>Download the <code>.zip</code> file, then open <strong>KernelSU</strong> (or Magisk / APatch) &rarr; <strong>Modules</strong> tab &rarr; <strong>Install module</strong>. Subsequent updates will be managed <strong>automatically</strong> inside the app!</span>
            </div>
        </div>
"""
        module_modals_html = f"""
    <div class="modal-overlay" id="qr-modal-module" onclick="if(event.target === this) this.classList.remove('active')">
        <div class="modal-content">
            <button class="modal-close" onclick="document.getElementById('qr-modal-module').classList.remove('active')">&times;</button>
            <p style="margin: 0 0 1.5rem 0; font-weight: 600; font-size: 1.1rem; color: var(--text-primary);">Scan to Download Magisk/KernelSU Module (.zip)</p>
            <img src="https://api.qrserver.com/v1/create-qr-code/?size=280x280&margin=1&data={urllib.parse.quote(module_download_url, safe='')}" alt="Module QR Code" style="background: white; padding: 0.5rem; border-radius: 12px; width: 280px; height: 280px;">
        </div>
    </div>
"""

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Download {app_display_name}</title>
    <link rel="stylesheet" href="./style.css">
</head>
<body class="app-page">
    <div class="container app-container">
        <a href="index.html" class="back-link">← Back to Apps List</a>
        <div class="header-content">
            <div class="app-icon-wrap">
                <img src="{icon_url}" alt="{app_display_name} icon" class="app-icon" onerror="this.parentElement.style.display='none'">
            </div>
            <h1>{app_display_name}</h1>
        </div>
        
        <div class="info-grid">
            <div class="info-item">
                <span class="info-label">Version</span>
                <span class="info-value">v{version}</span>
            </div>
            <div class="info-item">
                <span class="info-label">Patch Source</span>
                <span class="info-value">{patch_source_display}</span>
            </div>
            <div class="info-item">
                <span class="info-label">Architecture</span>
                <span class="info-value">{arch}</span>
            </div>
            <div class="info-item">
                <span class="info-label">Package ID</span>
                <span class="info-value" style="font-size: 0.9rem; word-break: break-all;">{app_id}</span>
            </div>
        </div>
        
        {info_card_html}
        
        <div class="download-card apk-card">
            <div class="download-card-header">
                <span class="card-badge apk-badge">📱 Standalone APK (Non-Root)</span>
            </div>
            <div class="filename-raw">
                File: <code>{filename}</code>
            </div>
            <div class="actions-group">
                <div class="action-row">
                    <a href="{download_url}" class="btn btn-download">Download APK</a>
                    <button class="btn-qr" onclick="document.getElementById('qr-modal-apk').classList.add('active')" title="Show APK QR Code">
                        {QR_SVG}
                    </button>
                </div>
                <div class="action-row">
                    <a href="{obtainium_link}" class="badge-obtainium">
                        <img src="https://raw.githubusercontent.com/ImranR98/Obtainium/main/assets/graphics/badge_obtainium.png" alt="Get it on Obtainium">
                    </a>
                    <button class="btn-qr" onclick="document.getElementById('qr-modal-obt').classList.add('active')" title="Show Obtainium QR Code">
                        {QR_SVG}
                    </button>
                </div>
            </div>
        </div>

        {module_section_html}

        {patches_list_html}
        
        <footer>
            <p>Source code and CI on GitHub: <a href="https://github.com/{owner}/{repo_name}" target="_blank" rel="noopener">{owner}/{repo_name}</a></p>
        </footer>
    </div>

    <div class="modal-overlay" id="qr-modal-apk" onclick="if(event.target === this) this.classList.remove('active')">
        <div class="modal-content">
            <button class="modal-close" onclick="document.getElementById('qr-modal-apk').classList.remove('active')">&times;</button>
            <p style="margin: 0 0 1.5rem 0; font-weight: 600; font-size: 1.1rem; color: var(--text-primary);">Scan to Download APK</p>
            <img src="https://api.qrserver.com/v1/create-qr-code/?size=280x280&margin=1&data={urllib.parse.quote(download_url, safe='')}" alt="APK QR Code" style="background: white; padding: 0.5rem; border-radius: 12px; width: 280px; height: 280px;">
        </div>
    </div>

    <div class="modal-overlay" id="qr-modal-obt" onclick="if(event.target === this) this.classList.remove('active')">
        <div class="modal-content">
            <button class="modal-close" onclick="document.getElementById('qr-modal-obt').classList.remove('active')">&times;</button>
            <p style="margin: 0 0 1.5rem 0; font-weight: 600; font-size: 1.1rem; color: var(--text-primary);">Scan to add in Obtainium</p>
            <img src="https://api.qrserver.com/v1/create-qr-code/?size=280x280&margin=1&data={urllib.parse.quote(obtainium_link, safe='')}" alt="Obtainium QR Code" style="background: white; padding: 0.5rem; border-radius: 12px; width: 280px; height: 280px;">
        </div>
    </div>

    {module_modals_html}
</body>
</html>
"""

    with open(os.path.join(out_dir, f"{slug}.html"), "w") as f:
        f.write(html_content)
    
    print(f"Generated {slug}.html for {filename}")

print("App pages generation complete.")


# Copy style.css to pages output directory
import shutil
css_source = os.path.join(os.path.dirname(__file__), "style.css")
css_dest = os.path.join(out_dir, "style.css")
if os.path.exists(css_source):
    shutil.copy2(css_source, css_dest)
    print("Copied style.css to pages directory.")

print("App pages generation complete.")
